name: Auto Update

on:
  schedule:
    - cron: '0 0 1 * *' # Runs at 00:00, on day 1 of the month

permissions:
  contents: read

jobs:
  precommit-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: dev
      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.8.x"
      - name: Run update
        run: |
            pip install pre-commit
            pre-commit autoupdate
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ secrets.PAT }}
          author: GitHub <noreply@github.com>
          add-paths: .pre-commit-config.yaml
          commit-message: Auto pre-commit update
          body: |
            Update pre-commit hooks to latest

            Auto generated
          branch: auto-update/precommit_update
          delete-branch: true
          title: Auto precommit update
          labels: automated-pr
          assignees: seladb
