name: Build and test
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight

env:
  BUILD_DIR: Dist
  CCACHE_DIR: ${{ github.workspace }}/.ccache
  CPPCHECK_VERSION: 2.9

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container: seladb/alpine317
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Checkout is performed out of the container and doesn't match our user
      - name: Fix checkout ownership
        run: chown -R "$(id -u):$(id -g)" "$GITHUB_WORKSPACE"

      - name: Install dependencies
        run: |
          apk update && apk add python3-dev
          git clone --branch $CPPCHECK_VERSION --single-branch https://github.com/danmar/cppcheck.git
          cd cppcheck && mkdir build && cd build && cmake .. && cmake --build . && cmake --install . && cd ../../ && rm -rf cppcheck
          python3 -m venv .venv
          . .venv/bin/activate
          python3 -m pip install pre-commit setuptools clang-format==19.1.6 clang-tidy==18.1.8

      - name: Run pre-commit
        run: |
          . .venv/bin/activate
          pre-commit run --all-files

      - name: Configure PcapPlusPlus for Static analysis
        run: cmake -S . -B "$BUILD_DIR"

      - name: Run clang-tidy on changed files
        run: |
          ./ci/clang-tidy-all.sh changed "$BUILD_DIR"

  linux:
    runs-on: ${{ matrix.runner }}
    container: seladb/${{ matrix.image }}
    strategy:
      matrix:
        include: # Check the images at https://github.com/seladb/PcapPlusPlus-DockerImages
          - runner: ubuntu-latest
            image: ubuntu2404
          - runner: ubuntu-latest
            image: rhel94
          - runner: ubuntu-latest
            image: fedora42
          - runner: ubuntu-latest
            image: alpine320

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Checkout is performed out of the container and doesn't match our user
      - name: Fix checkout ownership
        run: chown -R "$(id -u):$(id -g)" "$GITHUB_WORKSPACE"

      - name: Restore Ccache
        id: ccache-restore
        uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: |
            ${{ env.CCACHE_DIR }}
            !*.gcda
            !*.gcno
          key: ${{ matrix.image }}-ccache-${{ github.run_id }}
          restore-keys: |
            ${{ matrix.image }}-ccache

      - name: Configure MemPlumber
        run: cmake -S . -B "$BUILD_DIR"

      - name: Build MemPlumber
        run: cmake --build "$BUILD_DIR" -j

      - name: Test PcapPlusPlus
        run: |
          ctest --test-dir "$BUILD_DIR"

      - name: Save Ccache
        uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ steps.ccache-restore.outputs.cache-primary-key }}
